version: "3.9"
services:
  db:
    build: db/
    ports:
      - "5432:5432"
    networks: ['mynetwork']

  api:
    build: api/
    ports:
      - "8080:8080"
    networks: ['mynetwork']
#  redis:
#    image: "redis:alpine"

networks: {mynetwork: {}}
